# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoom.Client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoom.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='DiagramOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('diagram_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('diagram_owmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='zoom.DiagramOwner')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoom.Client')),
            ],
        ),
        migrations.AddField(
            model_name='diagramowner',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoom.Customer'),
        ),
        migrations.AddField(
            model_name='access',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoom.Customer'),
        ),
        migrations.AddField(
            model_name='access',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoom.Device'),
        ),
        migrations.AddField(
            model_name='access',
            name='do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoom.DiagramOwner'),
        ),
    ]
